# Generated by Django 5.1.6 on 2025-03-26 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=255)),
                ('main_condition_model', models.CharField(choices=[('COUNT_RACES', 'Count Races'), ('COUNT_TEAMS', 'Count Teams')], max_length=20)),
                ('main_condition_operator', models.CharField(choices=[('<', '<'), ('=', '='), ('>', '>'), ('contains', 'contains')], max_length=8)),
                ('main_condition_value', models.CharField(max_length=50)),
                ('subconditions', models.JSONField(default=list)),
            ],
        ),
    ]
