# Generated by Django 5.1.6 on 2025-03-22 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achievements', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievement',
            name='main_condition_operator',
            field=models.CharField(choices=[('<', '<'), ('=', '='), ('>', '>'), ('contains', 'contains')], max_length=8),
        ),
    ]
