databases:
  - name: ecm2434db
    plan: free
    databaseName: ecm2434
    user: ecm2434

services:
  - type: web
    plan: free
    name: ecm2434
    runtime: python
    buildCommand: "cd project && ./build.sh"  # Change the build command to navigate to the project folder
    startCommand: "cd project && python -m gunicorn ecm2434.asgi:application -k uvicorn.workers.UvicornWorker"  # Adjust the start command to run inside the project folder
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: ecm2434db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
