# Generated by Django 4.2.20 on 2025-03-17 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_usersettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='exeplore_mode_distance_traveled',
            field=models.IntegerField(default=0),
        ),
    ]
