# Generated by Django 5.1.6 on 2025-03-24 06:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('race', '0020_streak'),
        ('users', '0005_profile_exeplore_mode_distance_traveled'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='streak',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='race.streak'),
        ),
    ]
