# Generated by Django 4.2.20 on 2025-03-24 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_profile_streak'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='exeplore_mode_distance_traveled',
        ),
    ]
