# Generated by Django 4.2.11 on 2025-03-09 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LeaderboardEntry',
        ),
    ]
