# Generated by Django 4.2.11 on 2025-02-06 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('points_reward', models.IntegerField()),
                ('link_text', models.CharField(max_length=255)),
                ('link_url', models.URLField()),
            ],
        ),
    ]
