# Generated by Django 4.2.11 on 2025-02-08 09:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0002_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='link_text',
        ),
        migrations.RemoveField(
            model_name='task',
            name='link_url',
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
