# Generated by Django 4.2.19 on 2025-02-22 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('race', '0003_alter_raceentry_duration_alter_raceentry_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='raceentry',
            name='name',
            field=models.CharField(default='RaceEntry', max_length=255),
        ),
    ]
