# Generated by Django 4.2.19 on 2025-02-22 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('race', '0002_leaderboardentry'),
        ('race', '0004_raceentry_name'),
    ]

    operations = [
    ]
