# Generated by Django 4.2.19 on 2025-02-23 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('race', '0005_merge_0002_leaderboardentry_0004_raceentry_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='raceentry',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default='2024-02-23 12:00:00'),
            preserve_default=False,
        ),
    ]
