# Generated by Django 4.2.19 on 2025-03-03 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('race', '0006_raceentry_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='race',
            name='medal_requirements',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='raceentry',
            name='medal',
            field=models.CharField(default='None', max_length=6),
        ),
    ]
