# Generated by Django 5.1.6 on 2025-03-06 11:38

import race.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('race', '0007_race_medal_requirements_raceentry_medal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='race',
            name='medal_requirements',
            field=models.JSONField(default=list, validators=[race.models.validate_ascending_three_items]),
        ),
    ]
