# Generated by Django 5.1.6 on 2025-03-06 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('race', '0008_alter_race_medal_requirements'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='raceentry',
            name='duration',
        ),
    ]
