# Generated by Django 5.1.6 on 2025-03-06 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('race', '0009_remove_raceentry_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='raceentry',
            name='is_complete',
        ),
    ]
