# Generated by Django 5.1.6 on 2025-03-19 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('race', '0012_delete_leaderboardentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='raceentry',
            name='points',
            field=models.IntegerField(default=0),
        ),
    ]
