# Generated by Django 4.2.20 on 2025-03-17 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('race', '0012_delete_leaderboardentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='raceentry',
            name='num_completions',
            field=models.IntegerField(default=0),
        ),
    ]
