# Generated by Django 5.1.6 on 2025-03-20 01:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('race', '0013_raceentry_points'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='raceentry',
            name='points',
        ),
    ]
