# Generated by Django 5.1.6 on 2025-03-21 11:15

import race.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('race', '0013_raceentry_num_completions'),
    ]

    operations = [
        migrations.AddField(
            model_name='race',
            name='tags',
            field=models.JSONField(default=list, validators=[race.models.validate_list_of_strings]),
        ),
    ]
