# Generated by Django 5.1.6 on 2025-03-22 14:53

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('race', '0013_raceentry_num_completions'),
        ('race', '0015_raceentry_rank'),
    ]

    operations = [
        migrations.AddField(
            model_name='raceentry',
            name='rank',
            field=models.IntegerField(default=0),
        ),
    ]
