# Generated by Django 5.1.6 on 2025-03-22 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('race', '0014_race_tags'),
        ('race', '0017_alter_raceentry_rank'),
    ]

    operations = [
    ]
